<CFSET x = 41>
<CFSET x = x + 1>
<CFOUTPUT>#x#</CFOUTPUT>
<CFIF x EQ 42><CFOUTPUT>|IF</CFOUTPUT><CFELSE><CFOUTPUT>|ELSE</CFOUTPUT></CFIF>
<CFSWITCH expression="#x#"><CFCASE value="42"><CFOUTPUT>|SW</CFOUTPUT></CFCASE><CFDEFAULTCASE><CFOUTPUT>|DEF</CFOUTPUT></CFDEFAULTCASE></CFSWITCH>
<CFLOOP from="1" to="2" index="i"><CFOUTPUT>#i#</CFOUTPUT></CFLOOP>
<CFSET arr = [5, 6]><CFOUTPUT>|#arr[2]#</CFOUTPUT>
<CFSILENT>
<CFOUTPUT>HIDDEN</CFOUTPUT>
<CFSET z = 99>
</CFSILENT>
<CFOUTPUT>|#z#</CFOUTPUT>
<CFTRY>
<CFTHROW message="boom">
<CFCATCH><CFOUTPUT>|#cfcatch.message#</CFOUTPUT></CFCATCH>
</CFTRY>
