<!--- ImageGetIPTCMetadata / ImageGetIPTCTag verified byte-for-byte against
CF 2025 (RDS host). --->
<cfset sep = "~">
<cfset pi = ExpandPath("img_meta_i.jpg")>
<cfset FileWrite(pi, BinaryDecode("/9j/7QCGUGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAGkcAgAADVByb2JlSGVhZGxpbmUcAgUADFByb2JlQ2FwdGlvbhwCCgALUHJvYmVXcml0ZXIcAhkADVByb2JlS2V5d29yZHMcAlAAC1Byb2JlQnlsaW5lHAJ0AA9Db3B5cmlnaHQgUHJvYmUA/+AAEEpGSUYAAQEAAAEAAQAA/9sAQwADAgIDAgIDAwMDBAMDBAUIBQUEBAUKBwcGCAwKDAwLCgsLDQ4SEA0OEQ4LCxAWEBETFBUVFQwPFxgWFBgSFBUU/9sAQwEDBAQFBAUJBQUJFA0LDRQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU/8AAEQgAGAAgAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A+fKKKK/rU/nwKKKKACiiigAooooA/9k=", "base64"))>
<cfset imI = ImageRead(pi)>
<cfoutput>#sep#IPTC:#SerializeJSON(ImageGetIPTCMetadata(imI))#</cfoutput>
<cfoutput>#sep#BYLINE:#ImageGetIPTCTag(imI, "By-line")#</cfoutput>
<cfoutput>#sep#OBJNAME:#ImageGetIPTCTag(imI, "Object Name")#</cfoutput>
<cfoutput>#sep#URGENCY:#ImageGetIPTCTag(imI, "Urgency")#</cfoutput>
<cfoutput>#sep#MISSING:#ImageGetIPTCTag(imI, "NoSuchTag")#</cfoutput>
