<cfset st1 = StructNew()>
<cfset StructInsert(st1, "name", "test")>
<cfset StructInsert(st1, "value", 42)>
<cfset st2 = StructNew()>
<cfset StructInsert(st2, "z", 1)>
<cfset StructInsert(st2, "a", 2)>
<cfset StructInsert(st2, "m", 3)>
<cfset st3 = StructNew()>
<cfset StructInsert(st3, "Aa", 1)>
<cfset StructInsert(st3, "BB", 2)>
<cfset st4 = StructNew()>
<cfset StructInsert(st4, "BB", 1)>
<cfset StructInsert(st4, "Aa", 2)>
<cfset st5 = StructNew()>
<cfset StructInsert(st5, "mixed", "x")>
<cfset StructUpdate(st5, "MIXED", "y")>
<cfset st6 = StructNew()>
<cfset StructInsert(st6, "k1", 1)>
<cfset StructInsert(st6, "k2", 2)>
<cfset StructInsert(st6, "k3", 3)>
<cfset StructInsert(st6, "k4", 4)>
<cfset StructInsert(st6, "k5", 5)>
<cfset StructInsert(st6, "k6", 6)>
<cfset StructInsert(st6, "k7", 7)>
<cfset StructInsert(st6, "k8", 8)>
<cfset StructInsert(st6, "k9", 9)>
<cfset StructInsert(st6, "k10", 10)>
<cfset StructInsert(st6, "k11", 11)>
<cfset StructInsert(st6, "k12", 12)>
<cfset StructInsert(st6, "k13", 13)>
<cfoutput>#SerializeJSON(st1)#|#SerializeJSON(st2)#|#SerializeJSON(st3)#|#SerializeJSON(st4)#|#SerializeJSON(st5)#|#SerializeJSON(st6)#</cfoutput>
