<cfscript>
a = [1,2,3];
s = {x:1};
q = QueryNew("a");
writeOutput("1:[" & IsValid("array", a) & "]");
writeOutput("2:[" & IsValid("array", 5) & "]");
writeOutput("3:[" & IsValid("struct", s) & "]");
writeOutput("4:[" & IsValid("struct", 5) & "]");
writeOutput("5:[" & IsValid("query", q) & "]");
writeOutput("6:[" & IsValid("query", 5) & "]");
writeOutput("7:[" & IsValid("string", "hello") & "]");
writeOutput("8:[" & IsValid("string", 5) & "]");
writeOutput("9:[" & IsValid("numeric", "123") & "]");
writeOutput("10:[" & IsValid("numeric", "12.5") & "]");
writeOutput("11:[" & IsValid("numeric", "1e3") & "]");
writeOutput("12:[" & IsValid("numeric", "abc") & "]");
writeOutput("13:[" & IsValid("numeric", "12,5") & "]");
writeOutput("14:[" & IsValid("numeric", "$12") & "]");
writeOutput("15:[" & IsValid("numeric", "yes") & "]");
writeOutput("16:[" & IsValid("numeric", true) & "]");
writeOutput("17:[" & IsValid("integer", "5") & "]");
writeOutput("18:[" & IsValid("integer", "5.5") & "]");
writeOutput("19:[" & IsValid("integer", 5.5) & "]");
writeOutput("20:[" & IsValid("integer", 5) & "]");
writeOutput("21:[" & IsValid("boolean", "true") & "]");
writeOutput("22:[" & IsValid("boolean", "yes") & "]");
writeOutput("23:[" & IsValid("boolean", 1) & "]");
writeOutput("24:[" & IsValid("boolean", "abc") & "]");
writeOutput("25:[" & IsValid("uuid", CreateUUID()) & "]");
writeOutput("26:[" & IsValid("uuid", "invalid") & "]");
writeOutput("27:[" & IsValid("guid", "07F0F2A1-0000-0000-0000-000000000000") & "]");
writeOutput("28:[" & IsValid("guid", "invalid") & "]");
writeOutput("29:[" & IsValid("date", "2026-08-08") & "]");
writeOutput("30:[" & IsValid("date", "notadate") & "]");
writeOutput("31:[" & IsValid("time", "10:30:00") & "]");
writeOutput("32:[" & IsValid("time", "notatime") & "]");
writeOutput("33:[" & IsValid("url", "http://example.com") & "]");
writeOutput("34:[" & IsValid("url", "not a url") & "]");
writeOutput("35:[" & IsValid("email", "a@b.com") & "]");
writeOutput("36:[" & IsValid("email", "notanemail") & "]");
writeOutput("37:[" & IsValid("ssn", "123-45-6789") & "]");
writeOutput("38:[" & IsValid("ssn", "123456789") & "]");
writeOutput("39:[" & IsValid("telephone", "555-123-4567") & "]");
writeOutput("40:[" & IsValid("zipcode", "12345") & "]");
writeOutput("41:[" & IsValid("zipcode", "12345-6789") & "]");
writeOutput("42:[" & IsValid("zipcode", "1234") & "]");
writeOutput("43:[" & IsValid("creditcard", "4111111111111111") & "]");
writeOutput("44:[" & IsValid("creditcard", "1234567890123456") & "]");
writeOutput("45:[" & IsValid("xml", "<a/>") & "]");
writeOutput("46:[" & IsValid("xml", "notxml") & "]");
writeOutput("47:[" & IsValid("any", "x") & "]");
writeOutput("48:[" & IsValid("any", a) & "]");
writeOutput("50:[" & IsValid("binary", "abc") & "]");
writeOutput("51:[" & IsValid("variableName", "abc") & "]");
writeOutput("52:[" & IsValid("variableName", "1abc") & "]");
writeOutput("53:[" & IsValid("range", "5", 1, 10) & "]");
writeOutput("54:[" & IsValid("range", "15", 1, 10) & "]");
writeOutput("55:[" & IsValid("regex", "abc123", "^[a-z]+[0-9]+$") & "]");
writeOutput("56:[" & IsValid("regex", "123abc", "^[a-z]+[0-9]+$") & "]");
writeOutput("57:[" & IsValid("usdate", "08/08/2026") & "]");
writeOutput("58:[" & IsValid("usdate", "13/08/2026") & "]");
writeOutput("59:[" & IsValid("eurodate", "08/08/2026") & "]");
writeOutput("60:[" & IsValid("eurodate", "13/08/2026") & "]");
writeOutput("61:[" & IsValid("datetime_object", Now()) & "]");
writeOutput("62:[" & IsValid("float", "1.5") & "]");
writeOutput("63:[" & IsValid("numeric", "0x10") & "]");
</cfscript>
