import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const given = (process.argv[2] || '').trim();

let version = given;
if (!version) {
  try {
    version = execSync('git describe --tags --abbrev=0 2>/dev/null', {
      encoding: 'utf8',
    }).trim();
  } catch {
    /* no git or no tags in this checkout */
  }
}

const pkgPath = path.join(rootDir, 'package.json');
if (version) {
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  pkg.version = version;
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
  console.log(`set-version: package.json version -> ${version}`);
} else {
  // No explicit version and no git tag available (e.g. a bare docker build
  // without ADMIN_VERSION): fall back to the committed package.json version.
  version = JSON.parse(readFileSync(pkgPath, 'utf8')).version;
}

const built = new Date().toISOString().slice(0, 10);
const envDir = path.join(rootDir, 'src', 'environments');
mkdirSync(envDir, { recursive: true });
writeFileSync(
  path.join(envDir, 'version.ts'),
  `// Generated by scripts/set-version.mjs at build time - do not edit.\n` +
    `export const VERSION: string = ${JSON.stringify(version)};\n` +
    `export const BUILT: string = ${JSON.stringify(built)};\n`,
);
console.log(`set-version: src/environments/version.ts written (built ${built})`);